name: job test
on: push
jobs:
  web:
    name: deploy web
    runs-on: ubuntu-22.04
    defaults:
      run: 
        working-directory: ./web
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0   
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: web/package-lock.json
      - name: install dependency
        run: npm install
      - name: build
        run: npm run build
      - name: echo
        run: |
          pwd
          npm --version
          node --version
        
  
