name: job test
on: push
jobs:
  web:
    name: deploy web
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: cd
        run: |
          pwd
          cd web
          pwd
      - name: echo
        run: |
          pwd
          npm --version
          node --version
        
  
